// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include <frc2/command/SubsystemBase.h>
#include <rev/CANSparkMax.h>
#include <frc/Spark.h>

class Shooter: public frc2::SubsystemBase {
private:

frc::Spark m_pulleyMotor{5};
rev::CANSparkMax m_shooterLeft{2, rev::CANSparkMax::MotorType::kBrushless};
rev::CANSparkMax m_shooterRight{1, rev::CANSparkMax::MotorType::kBrushless};

public:
Shooter();

void Periodic() override;
void SimulationPeriodic() override;
void Expel();
void Intake();
};

