// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "commands/Move.h"

Move::Move(Drive* m_drive)
:m_drive(m_drive){

    // Use AddRequirements() here to declare subsystem dependencies
    // eg. AddRequirements(m_Subsystem);
    SetName("Move");
    AddRequirements(m_drive);
}

// Called just before this Command runs the first time
void Move::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void Move::Execute() {
    // get values from the Joystick
    //auto const & joystick = RobotContainer::getJoystick();

    ////TODO: get real joystick input
    //double ySpeed = 0.1;
    //double xSpeed = 0.2;
    //double zRotation = 0.3;

    //// pass values to the Drive subsystem
    //m_drive->Motivate(ySpeed, xSpeed, zRotation);
}

// Make this return true when this Command no longer needs to run execute()
bool Move::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void Move::End(bool interrupted) {

}

bool Move::RunsWhenDisabled() const {
    return false;
}