// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "commands/WinchUp.h"

WinchUp::WinchUp(Winch* m_winch)
:m_winch(m_winch){

    SetName("WinchUp");
    AddRequirements(m_winch);
}

// Called just before this Command runs the first time
void WinchUp::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void WinchUp::Execute() {
    m_winch->Raise();
}

// Make this return true when this Command no longer needs to run execute()
bool WinchUp::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void WinchUp::End(bool interrupted) {
    m_winch->WinchStop();
    wpi::outs() << "Winch Stop called from WinchUp.\n";
}

bool WinchUp::RunsWhenDisabled() const {
    return false;

}
