// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "subsystems/Winch.h"
#include <frc/smartdashboard/SmartDashboard.h>

Winch::Winch(){
    SetName("Winch");
    SetSubsystem("Winch");

    AddChild("Potentiometer", &m_potentiometer);
    AddChild("Double Solenoid", &m_winchSolenoid);
    AddChild("WinchMotor",    &m_winchMotor);

    m_winchMotor.SetInverted(false);
    m_winchSolenoid.Set(frc::DoubleSolenoid::Value::kOff);
}

void Winch::Periodic() {
    // Put code here to be run every loop
}

void Winch::SimulationPeriodic() {
}

// Put methods for controlling this subsystem
// here. Call these from Commands.
void Winch::Raise(){

    wpi::outs() << "Reverse Solenoid";
    // move actuator 
    m_winchSolenoid.Set(frc::DoubleSolenoid::Value::kForward);

    wpi::outs() << "Raise Winch.\n";
    // raise the winch
    m_winchMotor.Set(0.5);
}

void Winch::Lower(){

    wpi::outs() << "Reverse Solenoid";
    // move actuator
    m_winchSolenoid.Set(frc::DoubleSolenoid::Value::kForward);

    wpi::outs() << "Lower Winch.\n";
    // lower winch
    m_winchMotor.Set(-0.5);
}

void Winch::WinchStop(){
    wpi::outs() << "WinchStop.\n";
    m_winchMotor.Set(0.0);
    wpi::outs() << "Set Solenoid Forward.\n";
    m_winchSolenoid.Set(frc::DoubleSolenoid::Value::kReverse);
}